var data={
    CuM:{
        name:"铜矿",
        type:"s",
        level:0
    },
    FeM:{
        name:"铁矿",
        type:"s",
        level:0
    },
    CaM:{
        name:"石矿",
        type:"s",
        level:0
    },
    coalM:{
        name:"煤矿",
        type:"s",
        level:0
    },
    SiM:{
        name:"硅石",
        type:"s",
        level:0
    },
    TiM:{
        name:"钛石",
        type:"s",
        level:0
    },
    water:{
        name:"水",
        type:"l",
        level:0
    },
    oil:{
        name:"原油",
        type:"l",
        level:0
    },
    Cu:{
        name:"铜块",
        level:1,
        make:{
            item:[{
                id:"CuM",
                count:1
            }],
            time:1,
            count:1
        }
    },
    Fe:{
        name:"铁块",
        level:1,
        make:{
            item:[{
                id:"FeM",
                count:1
            }],
            time:1,
            count:1
        }
    },
    magnet:{
        name:"磁铁",
        level:1,
        make:{
            item:[{
                id:"FeM",
                count:1
            }],
            time:1.5,
            count:1
        }
    },
    glass:{
        name:"玻璃",
        level:1,
        make:{
            item:[{
                id:"CaM",
                count:2
            }],
            time:2,
            count:1
        }

    },
    eg:{
        name:"高能石墨",
        level:1,
        make:{
            item:[{
                id:"coalM",
                count:2
            }],
            time:2,
            count:1
        }
    },
    Si:{
        name:"高纯硅块",
        level:1,
        make:{
            item:[{
                id:"SiM",
                count:2
            }],
            time:2,
            count:1
        }
    },
    Ti:{
        name:"钛块",
        level:1,
        make:{
            item:[{
                id:"TiM",
                count:2
            }],
            time:2,
            count:1
        }
    },
    coil:{
        name:"磁线圈",
        level:2,
        make:{
            item:[{
                id:"magnet",
                count:2
            },{
                id:"Cu",
                count:1
            }],
            time:1,
            count:2
        }
    },
    steal:{
        name:"钢材",
        level:2,
        make:{
            item:[{
                id:"Fe",
                count:3
            }],
            time:3,
            count:1
        }
    },
    gear:{
        name:"齿轮",
        level:2,
        make:{
            item:[{
                id:"Fe",
                count:1
            }],
            time:1,
            count:1
        }
    },
    em:{
        name:"电机",
        level:3,
        make:{
            item:[{
                id:"Fe",
                count:2
            },{
                id:"magnet",
                count:1
            },{
                id:"gear",
                count:1
            }],
            time:2,
            count:1
        }
    },
    et:{
        name:"电磁涡轮",
        level:4,
        make:{
            item:[{
                id:"em",
                count:2
            },{
                id:"coil",
                count:2
            }],
            time:2,
            count:2
        }
    },
    superRing:{
        name:"超级磁场环",
        level:5,
        make:{
            item:[{
                id:"et",
                count:2
            },{
                id:"magnet",
                count:3,
            },{
                id:"eg",
                count:1,
            }],
            time:3,
            count:1
        }
    },
    roil:{
        name:"精炼油",
        level:2,
        make:{
            item:[{
                id:"oil",
                count:2
            }],
            time:4,
            count:2
        }
    },
    acid:{
        name:"硫酸",
        level:3,
        make:{
            item:[{
                id:"roil",
                count:6
            },{
                id:"CaM",
                count:8
            },{
                id:"water",
                count:4
            }],
            time:6,
            count:4
        }
    },
    ta:{
        name:"钛合金",
        level:4,
        make:{
            item:[{
                id:"steal",
                count:4
            },{
                id:"Ti",
                count:4
            },{
                id:"acid",
                count:8
            }],
            time:12,
            count:4
        }
    },
    tc:{
        name:"加力推进器",
        level:5,
        make:{
            item:[{
                id:"ta",
                count:5,
            },{
                id:"et",
                count:5
            }],
            time:6,
            count:1
        }
    },
    h2:{
        name:"氢",
        level:1,
        make:{
            item:[{
                id:"oil",
                count:2
            }],
            time:4,
            count:1
        }

    },
    oh:{
        name:"重氢",
        level:1,
        make:{
            item:[{
                id:"h2",
                count:10
            }],
            time:5,
            count:5
        }
    },
    drad:{
        name:"氘核燃料罐",
        level:5,
        make:{
            item:[{
                id:"oh",
                count:10
            },{
                id:"ta",
                count:1
            },{
                id:"superRing",
                count:1
            }],
            time:6,
            count:1
        }
    },
    cb:{
        name:"电路板",
        level:2,
        make:{
            item:[{
                id:"Cu",
                count:1
            },{
                id:"Fe",
                count:2
            }],
            time:1,
            count:2
        }
    },
    mc:{
        name:"微晶元件",
        level:2,
        make:{
            item:[{
                id:"Si",
                count:2
            },{
                id:"Cu",
                count:1
            }],
            time:2,
            count:1
        }
    },
    pb:{
        name:"处理器",
        level:3,
        make:{
            item:[{
                id:"mc",
                count:2
            },{
                id:"cb",
                count:2
            }],
            time:3,
            count:1
        }
    },
    plastic:{
        name:"塑料",
        level:3,
        make:{
            item:[{
                id:"roil",
                count:2
            },{
                id:"eg",
                count:1
            }],
            time:3,
            count:1
        }
    },
    oc:{
        name:"有机晶体",
        level:3,
        make:{
            item:[{
                id:"plastic",
                count:2
            },{
                id:"roil",
                count:1
            },{
                id:"water",
                count:1
            }],
            time:6,
            count:1
        }
    },
    Tis:{
        name:"钛晶石",
        level:4,
        make:{
            item:[{
                id:"Ti",
                count:3
            },{
                id:"oc",
                count:1
            }],
            time:4,
            count:1
        }
    },
    grap:{
        name:"石墨烯",
        level:2,
        make:{
            item:[{
                id:"eg",
                count:3
            },{
                id:"acid",
                count:1
            }],
            time:3,
            count:2
        }
    },
    cc:{
        name:"卡西米尔晶体",
        level:5,
        make:{
            item:[{
                id:"grap",
                count:2
            },{
                id:"h2",
                count:12
            },{
                id:"Tis",
                count:1
            }],
            time:4,
            count:1
        }
    },
    tglass:{
        name:"钛玻璃",
        level:3,
        make:{
            item:[{
                id:"Ti",
                count:2
            },{
                id:"water",
                count:2
            },{
                id:"glass",
                count:2
            }],
            time:3,
            count:2
        }
    },
    pfilter:{
        name:"位面过滤器",
        level:6,
        make:{
            item:[{
                id:"tglass",
                count:2
            },{
                id:"cc",
                count:1
            }],
            time:12,
            count:1
        }
    },
    qchip:{
        name:"量子芯片",
        level:8,
        make:{
            item:[{
                id:"pfilter",
                count:2
            },{
                id:"pb",
                count:2
            }],
            time:6,
            count:1
        }
    },
    cpipe:{
        name:"碳纳米管",
        level:2,
        make:{
            item:[{
                id:"grap",
                count:3
            },{
                id:"Ti",
                count:1
            }],
            time:4,
            count:2
        }
    },
    fm:{
        name:"框架材料",
        level:4,
        make:{
            item:[{
                id:"cpipe",
                count:4
            },{
                id:"Si",
                count:1
            },{
                id:"ta",
                count:1
            }],
            time:6,
            count:1
        }
    },
    prism:{
        name:"棱镜",
        level:3,
        make:{
            item:[{
                id:"glass",
                count:3
            }],
            time:2,
            count:2
        }
    },
    phc:{
        name:"光子合并器",
        level:4,
        make:{
            item:[{
                id:"cb",
                count:1
            },{
                id:"prism",
                count:2
            }],
            time:3,
            count:1
        }
    },
    solars:{
        name:"太阳帆",
        level:5,
        make:{
            item:[{
                id:"phc",
                count:1
            },{
                id:"grap",
                count:1
            }],
            time:4,
            count:2
        }
    },
    dsc:{
        name:"戴森球组件",
        level:6,
        make:{
            item:[{
                id:"solars",
                count:3
            },{
                id:"fm",
                count:3
            },{
                id:"pb",
                count:3
            }],
            time:8,
            count:1
        }
    },
    rocket:{
        name:"小型运载火箭",
        level:8,
        make:{
            item:[{
                id:"drad",
                count:2
            },{
                id:"qchip",
                count:2
            },{
                id:"dsc",
                count:2
            }],
            time:6,
            count:1
        }
    }

    
}